services:
  test:
    build: .
    ports: 
      - 8888:80
    environment:
      - START_SERVER_URL=http://backup.elend.name:1/
      - PING_URL=http://192.168.0.5:8080/
      - PING_TIMEOUT=1000
      - CONNECTED_TIMER=30000
      - DISCONNECTED_TIMER=10000