import { Type, type Static } from '@sinclair/typebox';

// Generated by:
// https://sinclairzx81.github.io/typebox-workbench/?share=ZXhwb3J0IHR5cGUgU3RhdHVzVW5rbm93biA9IHtzdGF0dXM6ICJ1bmtub3duIn07CmV4cG9ydCB0eXBlIFN0YXR1c1N0b3BwZWQgPSB7c3RhdHVzOiAic3RvcHBlZCJ9OwpleHBvcnQgdHlwZSBTdGF0dXNTdGFydGluZyA9IHtzdGF0dXM6ICJzdGFydGluZyJ9OwpleHBvcnQgdHlwZSBTdGF0dXNTdGFydGVkID0ge3N0YXR1czogInN0YXJ0ZWQifTsKZXhwb3J0IHR5cGUgU3RhdHVzU3RvcHBpbmcgPSB7c3RhdHVzOiAic3RvcHBpbmcifTsKZXhwb3J0IHR5cGUgUG93ZXJTdGF0dXMgPSBTdGF0dXNVbmtub3duIHwgU3RhdHVzU3RvcHBlZCB8IFN0YXR1c1N0YXJ0aW5nIHwgU3RhdHVzU3RhcnRlZCB8IFN0YXR1c1N0b3BwaW5nOw%3D%3D
// export type StatusUnknown = { status: "unknown"; };
// export type StatusStopped = { status: "stopped"; };
// export type StatusStarting = { status: "starting"; };
// export type StatusStarted = { status: "started"; };
// export type StatusStopping = { status: "stopping"; };
// export type PowerStatus = StatusUnknown | StatusStopped | StatusStarting | StatusStarted | StatusStopping;

/**
 * @public
 */
export type StatusUnknown = Static<typeof StatusUnknown>;
/**
 * @public
 */
export const StatusUnknown = Type.Object({
  status: Type.Literal('unknown')
});

/**
 * @public
 */
export type StatusStopped = Static<typeof StatusStopped>;
/**
 * @public
 */
export const StatusStopped = Type.Object({
  status: Type.Literal('stopped')
});

/**
 * @public
 */
export type StatusStarting = Static<typeof StatusStarting>;
/**
 * @public
 */
export const StatusStarting = Type.Object({
  status: Type.Literal('starting')
});

/**
 * @public
 */
export type StatusStarted = Static<typeof StatusStarted>;
/**
 * @public
 */
export const StatusStarted = Type.Object({
  status: Type.Literal('started')
});

/**
 * @public
 */
export type StatusStopping = Static<typeof StatusStopping>;
/**
 * @public
 */
export const StatusStopping = Type.Object({
  status: Type.Literal('stopping')
});

/**
 * @public
 */
export type PowerStatus = Static<typeof PowerStatus>;
/**
 * @public
 */
export const PowerStatus = Type.Union([
  StatusUnknown,
  StatusStopped,
  StatusStarting,
  StatusStarted,
  StatusStopping
]);
